services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    env_file: ./.env
    restart: on-failure
    # depends_on:
    #   - wordpress
    # networks:
    #   - inception
    #  volumes:
    #   - wordpress:/var/www/wordpress   # share WordPress files

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file: ./.env
    restart: on-failure
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    # networks:
    #   - inception
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: ./.env
    restart: on-failure
    # depends_on:
    #   - mariadb
    # networks:
    #   - inception
    # volumes:
    #   - wordpress:/var/www/wordpress
    # expose:
    #   - "9000"
# networks:
#   inception:
#     driver: bridge

#TODO: volumes must mount last as everything work
# Persistent volumes (host paths in /home/akurmyza/data)
# volumes:
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${DATA_PATH}/mariadb

# wordpress:
#   driver: local
#   driver_opts:
#     type: none
#     o: bind
#     device: ${DATA_PATH}/wordpress
